### ISSUE TITLE
Close icon not showing

### ISSUE THREAD

**Issue by marcosg** [RobinBrouwer/gritter#67]
In app/assets/stylesheets/gritter.css.scss

```SCSS
.gritter-css2 .gritter-close {
  background:url(asset-url('gritter.png')) no-repeat left top;
}
.gritter-css3 .gritter-close {
  background:url(asset-url('gritter-close.png')) no-repeat;
}
```

should be:
```SCSS
.gritter-css2 .gritter-close {
  background: asset-url('gritter.png') no-repeat left top;
}
.gritter-css3 .gritter-close {
  background: asset-url('gritter-close.png') no-repeat;
}
```

The `url(asset-url(` pattern is also used in other places in the file. I'm not sure what these do, but they should also probably be corrected.
